baseurl = "/"
title = "Simple Lookups"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Simple Lookups"
    info = "A simple .NET library for database lookup tables."
    description = "Simple Lookups - A simple .NET library for database lookup tables."
    keywords = "developer"
    # avatarurl = "images/profile.jpeg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    hidecredits = true
    hidecopyright = false

    rtl = false

    math = true
    since = "2013"

[permalinks]
  posts = "/:year/:month/:title/"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/simplelookups/"

# Menu links
[[menu.main]]
    name = "Download"
    weight = 1
    url = "/download/"
[[menu.main]]
    name = "News"
    weight = 2
    url = "/news/"
[[menu.main]]
    name = "Getting Started"
    weight = 3
    url = "/getting-started/"
[[menu.main]]
    name = "Documentation"
    weight = 5
    url = "/documentation/"
[[menu.main]]
    name = "Contact"
    weight = 8
    url  = "/contact/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
